//! Raw libghostty-vt bindings, generated by bindgen from the installed headers.
//!
//! Nothing here is hand-written: the whole point is that no signature is
//! guessed. Safe wrappers live in [`crate::vt`].

#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(dead_code, clippy::all)]

include!(concat!(env!("OUT_DIR"), "/libghostty_vt.rs"));
